# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).

name: CI

on: [push, pull_request] # on all pushes and PRs

jobs:
  ros1_bridge:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling-ros1-bridge-focal
    steps:
      - uses: actions/checkout@v2
      - name: Build ros1-bridge
        run: |
          chmod +x "${GITHUB_WORKSPACE}/build_bridge.sh "
          "${GITHUB_WORKSPACE}/build_bridge.sh"


